### ISSUE TITLE
'util' library for convenience functions?

### ISSUE THREAD

**Issue by gavanderhoorn** [onerobotics/KUnit#4]
More of a question really than a real issue, but I'm wondering if there is place in KUnit for something like a library of convenience functions that helps avoid repeating code in test suites.

I've been doing a lot of network programming lately, and in many tests I need to make sure that the nr of bytes remaining in a file descriptor buffer is equal to some nr. This is done using `BYTES_AHEAD(..)`, with some error checking code surrounding it, then finally a `kunit_eq_int(..)`.
For my own tests, I've created a small lib that has a bunch of these as functions, so I can just do `assrt_bytes(..)`.

Naming aside, what are your thoughts on putting some of that into KUnit itself?

Also: what should be the behaviour of such a routine when things not part of the test (such as `BYTES_AHEAD(..)` fail for some reason? Right now I just fail the test, but on some level that is not really fair (although you could argue that without access to `b_avail` the test can only fail).

**Comment by unreal** [comment]
> Naming aside, what are your thoughts on putting some of that into KUnit itself?

For now, I have no issue putting various convenience functions inside of KUnit, since there's no real good way of including various libraries within a project. It's much easier to just include one, that's why I put `strlib.*` directly into KUnit.

Ideally `ktrans` would take a list of directories to search for `%INCLUDE`s, but I won't hold my breath... I'd like to write a quick command-line utility that would prepare a build directory based on the `%INCLUDE` statements and a list of directories passed to the translator as a search path in addition to the current local directory and robot support dir.

> Also: what should be the behaviour of such a routine when things not part of the test (such as BYTES_AHEAD(..) fail for some reason? Right now I just fail the test, but on some level that is not really fair (although you could argue that without access to b_avail the test can only fail)

I think it would be better to fail the test with an error message over causing a panic/abort or something.

**Comment by gavanderhoorn** [comment]
> Ideally `ktrans` would take a list of directories to search for `%INCLUDE`s, but I won't hold my breath... I'd like to write a quick command-line utility that would prepare a build directory based on the `%INCLUDE` statements and a list of directories passed to the translator as a search path in addition to the current local directory and robot support dir.

Slightly off-topic, but as I ran out of breath (or patience?) waiting for multiple include dir support, I put together [rossum](https://github.com/gavanderhoorn/rossum), which basically does what you describe (although it does not rely on `INCLUDE` statements, but requires the user to explicitly state dependencies). It's not the prettiest code, but it seems to do the job.

**Comment by gavanderhoorn** [comment]
Also off-topic: refactored & split off the include dir support into [ktransw_py](https://github.com/gavanderhoorn/ktransw_py). Stand-alone from `rossum` now.

**Comment by unreal** [comment]
Awesome! Looking forward to using both projects.

Now that rossum and ktransw exist, I think a project that would enhance the KAREL "standard library" with additional routines for strings, file operators, etc. would be great.

**Comment by gavanderhoorn** [comment]
re: stdlib: yeah. I've been doing that already. I think your `strlib` is a good candidate.
