### ISSUE TITLE
ability to enable/disable HTML output formatting

### ISSUE THREAD

**Issue by unreal** [onerobotics/KUnit#5]
Command-line via `curl http://robot/KAREL/my_test` is a bit easier than reloading a browser window.

**Comment by gavanderhoorn** [comment]
Yes, this would be really nice.

That would also allow for easier integration with command line scripts that could automate building, deploying and running tests on controllers.

**Comment by gavanderhoorn** [comment]
Would it be an idea to output something like JSON or YAML?

**Comment by unreal** [comment]
I can see JSON being useful.

I can see two ways to accomplish:

1. Set the output type via GET request e.g. `http://robot/KAREL/my_test?kunit_output=html`
2. Add an argument to `kunit_init()` for output type

Option 1 is nice since you could get different output depending on your environment, but it would require a global variable in the test file. I think you would have to pass the setting through `kunit_init()` either way.

Another option is to add functionality to `kunit.kl` itself to run tests located in other files via RUN_TASK and a semaphore... e.g. `http://robot/KAREL/kunit?filename=test_strlib&output=html`

**Comment by gavanderhoorn** [comment]
Extending `kunit.kl` to act as a driver for tests in other programs is a nice idea. I assume the semaphore is for synchronising the testcase with the driver? Instead of locking, we could probably get the same behaviour with a producer-consumer scheme: have the testprogram place (a) token(s) in a pipe / shared queue (to indicate progress fi) and have the driver wait for completion that way (perhaps even with a timeout).

A bit more complicated than a semaphore, but also more flexible (and we could potentially run multiple tests in parallel).

**Comment by unreal** [comment]
I did a quick test using both `RUN_TASK` and `CALL_PROG` to drive a test file.  `CALL_PROG` works out of the box, but the `WRITE`s to the response file in `kunit_test` need to be removed when running asynchronously. Semantically, it's probably better to produce the dots and Fs in `kunit_output` anyway.

Yes, I was thinking of using a semaphore to indicate a file is done with all of it's tests, but that would require `POST_SEMA` to be used at the end of the test program or a routine like `kunit_done()`... `GET_TSK_INFO` could also be used with a small loop/delay.

I'm curious about the pipe/token method. The main `kunit` task is going to have to wait for all the other tests to finish before preparing the output somehow, and `PEND_SEMA` already has built-in timeout functionality.

**Comment by unreal** [comment]
Got pretty off-track with the original output issue, but I did some hacking to support running multiple tests in parallel: https://github.com/onerobotics/KUnit/tree/test_runner

**Comment by unreal** [comment]
I should probably mention that there may be significant overhead in constantly opening and closing file pipes e.g.  https://github.com/onerobotics/KUnit/blob/test_runner/src/kunit.kl#L102

I'm sure there's a better way e.g. each test file can grab their own handle on the pipe file before running any tests?
