### ISSUE TITLE
(KUNIT, 444) Cannot use specified program

### ISSUE THREAD

**Issue by yura** [onerobotics/KUnit#6]
Trying to execute test suite by:

`http://127.0.0.1/karel/kunit?filenames=test_kunit&output=html`

And got:

```ERROR: Program did not complete see error log for more details```

with details:

```
1063" 15-AUG-18 00:17:14 " INTP-368 (KUNIT, 444) Cannot use specified program" MEMO-073 Program does not exist                   " STOP.L                        00000110" act"
```

I suppose the problem is in the line 444 of the `kunit.kl` file which contains:

```pascal
  split_str(filenames, ',', filenames_a)
```

**Comment by unreal** [comment]
Try loading `vendor/strings.pc` onto your virtual.

**Comment by unreal** [comment]
I am also looking at `src/includes/vendor/strings.h.kl` which reference `strlib`. This may be a typo. If you've loaded `strings.pc`, you may have to update `strings.h.kl` to reference `strings`, not `strlib`. Please let me know if this fixes the issue.

**Comment by yura** [comment]
```
KUnit v1.0.0

....F..............

Finished in 0.004 seconds
4750.0 tests/sec, 9000.0 assertions/sec

 1) Failure:
kunit_fail()
this is not a real failure... ignore me

 1) Failure:
kunit_test() on fail
this one is responsible for the F

19 tests, 36 assertions, 0 failures
```

on testing KUnit

**Comment by unreal** [comment]
Weirdly enough, that is the expected output from testing KUnit. The tests reset some internals which should be considered private, and that's why there are e.g. two failures both labeled as 1), only a single F in the output and a report of 0 failures.

Thanks for the pull request. Closing this issue per pull request fix.
