### ISSUE TITLE
Request source code strings.kl

### ISSUE THREAD

**Issue by SketchyAlison** [onerobotics/KUnit#8]
Hello!

Really excited about this testing framework, but ran into a roadblock while trying to upload and test it for the first time. The file <code>vendor/strings.pc</code> isn't accepted by the robot due to program being too old. Would you be able to supply the <code>strings.kl</code> file so that I can recompile it?

Alison

**Comment by gavanderhoorn** [comment]
I'm sure @unreal will respond, but in the meantime: `strings.kl` is hosted at [onerobotics/strings](https://github.com/onerobotics/strings).

**Comment by SketchyAlison** [comment]
Oh, perfect! Didn't see that, thanks so much.

**Comment by unreal** [comment]
I'm glad @gavanderhoorn was able to help you!

I'm not sure why I vendored the binary in the first place... need to create a new issue to perhaps add onerobotics/strings as a submodule in /vendor.
